# Markdownlint configuration
# https://github.com/DavidAnson/markdownlint

# Disable line length check (tables and code examples often exceed 80 chars)
MD013: false

# Allow duplicate headings in different sections
MD024:
  siblings_only: true

# Disable table column alignment enforcement
MD060: false

# Allow code blocks without language specifiers (for ASCII diagrams)
MD040: false
